# export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
CASE_SENSITIVE="true"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=black,bold'

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# see 'man strftime' for details.
HIST_STAMPS="%m/%d %H:%M:%S"

plugins=(git zsh-syntax-highlighting zsh-autosuggestions
	docker kubectl oc helm terraform
)
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#############
source $HOME/hi/cli/shell/zsh/theme-extension
#bindkey ???
source $HOME/hi/cli/shell/shell_aliases
